from django.conf.urls import url
from stats import views, cookies, imgviews

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    url(r'^consistency/(.*)', views.consistency),
    url(r'^sgoyt/(.*)', views.sgoyt),
    url(r'^playlogging/(.*)', views.playLogging),
    url(r'^dimesbydesigner/(.*)', views.dimesByDesigner),
    url(r'^selections/(.*)', views.viewSelections),
    url(r'^selector/(.*)', views.selector),
    url(r'^collection/(.*)', views.collection),
    url(r'^collections/(.*)', views.manageCollections),
    url(r'^editCollection/(.*)', views.editCollection),
    url(r'^deleteCollection/(.*)', views.deleteCollection),
    url(r'^viewCollection/(.*)', views.viewCollection),
    url(r'^saveManageCollection/$', views.saveManageCollection),
    url(r'^submit/$', views.ajaxSubmit),
    url(r'^calendar/(.*)', views.gamesCalendar),
    url(r'^choose/(.*)', views.choose),
    url(r'^gini/(.*)', views.gini),
    url(r'^json/(.*)', views.json),
    url(r'^features/(.*)', views.featureList),
    url(r'^locations/(.*)', views.locations),
    url(r'^ipod/(.*)', views.ipod),
    url(r'^trade/(.*)', views.trade),
    url(r'^mobile/(.*)', views.ipod),
    url(r'^playscsv/(.*)', views.playscsv),
    url(r'^whatif/(.*)', views.whatif),
    url(r'^cookies/$', cookies.cookies),
    url(r'^rankings/(.*)', views.rankings),
    url(r'^normrankings/(.*)', views.normrankings),
    url(r'^geeks/$', views.listOfGeeks),
    url(r'^updates/(.*)', views.updates),
    url(r'^refreshPage/(.*)', views.refresh, name='full-refresh'),
    url(r'^quickRefresh/(.*)', views.quickRefresh, name='quick-refresh'),
    url(r'^result/(.*)', views.result),
    url(r'^tabbed/(.*)', views.tabbed),
    url(r'^favourites/(.*)', views.favourites),
    url(r'^generic/(.*)', views.generic),
    url(r'^favourites2/(.*)', views.favourites2),
    url(r'^unusual/(.*)', views.unusual),
    url(r'^multiyear/(.*)', views.multiyear),
    url(r'^yearcomparison/(.*)', views.comparativeYears),
    url(r'^plays/(.*)', views.plays),
    url(r'^catgraphs/(.*)', views.categoryGraphs),
    url(r'^year/(.*)', views.year),
    url(r'^server/(.*)', views.server),
    url(r'^checklist/(.*)', views.checklist),
    url(r'^crazy/(.*)', views.crazy),
    url(r'^meta/$', views.meta),
    url(r'^numplayers/(.*)', views.numplayers),
    url(r'^series/(.*)', views.series),
    url(r'^cat/(.*)', views.category),
    url(r'^playrate/(.*)', views.playrate),
    url(r'^image/lag/(.*)', imgviews.lagHistogram),
    url(r'^image/newPlays/(.*)', imgviews.newPlays),
    url(r'^image/fpvr/(.*)', imgviews.firstPlayVsRating),
    url(r'^image/mpct/(.*)', imgviews.mostPlayedCumulativeTimeline),
    url(r'^image/rbpy/(.*)', imgviews.ratingByPublishedYear),
    url(r'^image/rbpyu/(.*)', imgviews.ratingByPublishedYearUpsideDown),
    url(r'^image/pogo/(.*)', imgviews.pogo),
    url(r'^image/pbm/(.*)', imgviews.pbmGraph),
    url(r'^image/pbq/(.*)', imgviews.playsByQuarter),
    url(r'^image/morgan/(.*)', imgviews.morgansPieCharts),
    url(r'^image/morepie/(.*)', imgviews.morePieCharts),
    url(r'^image/cat/(.*)', imgviews.category),
    url(r'^image/playrate/(.*)', imgviews.playrate),
    url(r'^image/playrateown/(.*)', imgviews.playrateown),
    url(r'^image/lifetime/(.*)', imgviews.lifetime),
    url(r'^image/lbr/(.*)', imgviews.lifetimeByRating),
    url(r'^index.html$', views.frontPage),
    url(r'^australia.html$', views.australiaFrontPage),
    url(r'^$', views.frontPage)

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/(.*)', admin.site.root),
]
