#!/usr/bin/env python

import sys
sys.path.append(".")

BETWEEN_POPULATES = 540

def loadGameFiles(db):
    import time, populateFiles
    finish = time.time() + BETWEEN_POPULATES
    populateFiles.main(db, finish)

import sys, mydb, logging, sitedata, time
logging.basicConfig(filename=sitedata.logfile,level=logging.DEBUG)
logging.info("Downloader starts at %s" % (time.ctime(),))
toFix = sys.argv[1:]
db = mydb.MyDB()
for geek in toFix:
    print db.execute("update files set lastUpdate = null where geek = '%s' and processMethod != 'processGame'" % geek)
    print "Reset %s" % geek
db.close()
db = mydb.MyDB()
loadGameFiles(db)
db.close()

